-- Active: 1688058502640@@127.0.0.1@5432@PneumlOT@public
-- Generated by the database client, not guaranteed complete.
CREATE TABLE IF NOT EXISTS pneumiot.board(
    event_id SERIAL NOT NULL,
    board_id character varying(50) NOT NULL,
    PRIMARY KEY(event_id)
);

INSERT INTO pneumiot.board (board_id, pm_sensor, ozone_sensor, humidity_sensor, temperature_sensor, log_time)
VALUES( '123-abc-456-def', (RANDOM() * 100)::numeric(4,2), (RANDOM() * 100)::numeric(4,2), (RANDOM() * 100)::numeric(4,2), (RANDOM() * 100)::numeric(4,2),
       CURRENT_TIMESTAMP AT TIME ZONE 'UTC' - INTERVAL '1 hours' + INTERVAL '1 minute');


DO $$
DECLARE
    counter INTEGER := 1;
BEGIN
    WHILE counter <= 200 LOOP
        INSERT INTO pneumiot.board (board_id, pm_sensor, ozone_sensor, humidity_sensor, temperature_sensor, log_time)
        VALUES ('123-abc-456-def', (RANDOM() * 100)::numeric(4,2), (RANDOM() * 100)::numeric(4,2), (RANDOM() * 100)::numeric(4,2), (RANDOM() * 100)::numeric(4,2),
               CURRENT_TIMESTAMP AT TIME ZONE 'UTC' - INTERVAL '8 hour' + INTERVAL '1 minute' * counter);
        
        counter := counter + 1;
    END LOOP;
END $$;


DELETE FROM pneumiot.board WHERE board_id = '123-abc-456-def';

SELECT * FROM pneumiot.board;

SELECT pneumiot.board.sensor_id, sensor_type, sensor_units, min_value, max_value
FROM pneumiot.sensor
INNER JOIN pneumiot.board
ON pneumiot.board.sensor_id = pneumiot.sensor.sensor_id Where pneumiot.board.board_id = '123-abc-456-def';




select * from pneumiot.patient;



select pneumiot.sensor.sensor_type from pneumiot.sensor JOIN pneumiot.board ON pneumiot.board.sensor_id = pneumiot.sensor.sensor_id 
Where pneumiot.board.board_id = '123-abc-456-def';


DELETE FROM pneumiot.doctor
WHERE pneumiot.patient.patient_id IN (
  SELECT pneumiot.patient.patient_id
  FROM pneumiot.patient
  INNER JOIN pneumiot.board ON pneumiot.patient.board_id = pneumiot.board.board_id
  Where pneumiot.patient.board_id = '123-abc-456-def'
  GROUP BY pneumiot.patient.patient_id
);

DELETE FROM pneumiot.doctor
WHERE pneumiot.doctor.patient_id IN (
    SELECT patient.patient_id
    FROM pneumiot.patient
    INNER JOIN pneumiot.board ON pneumiot.patient.board_id = pneumiot.board.board_id
    WHERE pneumiot.patient.board_id = '123-abc-456-def'
    GROUP BY patient.patient_id
);

SELECT board_id, ARRAY_AGG(sensor_id) AS sensor_ids
FROM pneumiot.board
WHERE board_id = '123-abc-456-def'
GROUP BY board_id;


select * from pneumiot.worker;

Select board_id, array_agg(sensor_id) as sensor_ids
FROM pneumiot.board WHERE pneumiot.board.board_id IN(
    
);

select * from pneumiot.board INNER JOIN pneumiot.patient ON pneumiot.board.board_id = pneumiot.patient.board_id Where pneumiot.patient.patient_id = '76438301D';

select pneumiot.patient.patient_id from pneumiot.patient 
JOIN pneumiot.doctor ON pneumiot.doctor.patient_id = pneumiot.patient.patient_id 
WHERE pneumiot.doctor.worker_id = '24183922C' GROUP BY pneumiot.patient.patient_id;


SELECT pneumiot.board.board_id, array_agg(sensor_id) as sensor_ids
FROM pneumiot.board
INNER JOIN pneumiot.patient ON pneumiot.board.board_id = pneumiot.patient.board_id
WHERE pneumiot.patient.patient_id IN (
  SELECT pneumiot.patient.patient_id
  FROM pneumiot.patient 
  JOIN pneumiot.doctor ON pneumiot.doctor.patient_id = pneumiot.patient.patient_id 
  WHERE pneumiot.doctor.worker_id = '24183922C'
) GROUP BY pneumiot.board.board_id;


SELECT pneumiot.board.board_id, array_agg(pneumiot.sensor.sensor_type) as sensor_types
FROM pneumiot.board
JOIN pneumiot.sensor ON pneumiot.board.sensor_id = pneumiot.sensor.sensor_id GROUP BY pneumiot.board.board_id;


SELECT * FROM pneumiot.doctor;


SELECT pneumiot.patient.patient_id
  FROM pneumiot.patient 
  JOIN pneumiot.doctor ON pneumiot.doctor.patient_id = pneumiot.patient.patient_id 
  WHERE pneumiot.doctor.worker_id = '24183922C';


SELECT pneumiot.board.board_id
FROM pneumiot.board
INNER JOIN pneumiot.patient ON pneumiot.board.board_id = pneumiot.patient.board_id
WHERE pneumiot.patient.patient_id IN (
  SELECT pneumiot.patient.patient_id
  FROM pneumiot.patient 
  JOIN pneumiot.doctor ON pneumiot.doctor.patient_id = pneumiot.patient.patient_id 
  WHERE pneumiot.doctor.worker_id = '24183922C'
) GROUP BY pneumiot.board.board_id;

SELECT pneumiot.board.board_id, array_agg(pneumiot.sensor.sensor_type) as sensor_types
FROM pneumiot.board 
INNER JOIN pneumiot.sensor ON pneumiot.board.sensor_id = pneumiot.sensor.sensor_id
WHERE pneumiot.board.board_id IN (
    SELECT pneumiot.board.board_id
    FROM pneumiot.board
    INNER JOIN pneumiot.patient ON pneumiot.board.board_id = pneumiot.patient.board_id
    WHERE pneumiot.patient.patient_id IN (
        SELECT pneumiot.patient.patient_id
        FROM pneumiot.patient 
        JOIN pneumiot.doctor ON pneumiot.doctor.patient_id = pneumiot.patient.patient_id 
        WHERE pneumiot.doctor.worker_id = '24183922C'
    )
)
GROUP BY pneumiot.board.board_id;


select pneumiot.doctor.worker_id from pneumiot.doctor
INNER JOIN pneumiOT.patient ON pneumiot.doctor.patient_id = pneumiot.patient.patient_id
WHERE pneumiot.patient.patient_id IN (
    select pneumiot.patient.patient_id from pneumiot.board
    JOIN pneumiot.patient
    ON pneumiot.board.board_id = pneumiot.patient.board_id
    Where pneumiot.board.board_id = '123-abc-456-def'
);



SELECT board_id, ARRAY_AGG(sensor_id) AS sensor_ids
FROM pneumiot.board
GROUP BY board_id;


SELECT board_id, ARRAY_AGG(sensor_id) AS sensor_ids
FROM pneumiot.board
GROUP BY board_id;

select board_id, sensor_id from pneumiot.board Where board_id = '123-abc-456-def';

select pneumiot.patient.patient_id from pneumiot.patient INNER JOIN pneumiot.board ON pneumiot.patient.board_id = pneumiot.board.board_id GROUP BY pneumiot.patient.patient_id;
select patient_id, pneumiot.board.board_id from pneumiot.board inner join pneumiot.patient ON pneumiot.board.board_id = pneumiot.patient.board_id Where pneumiot.patient.board_id = '123-abc-456-def';

delete from pneumiot.patient Where board_id = '123-abc-456-def';


Select DISTINCT(pneumiot.board.board_id), pneumiot.patient.patient_id from pneumiot.board inner JOIN pneumiot.patient ON pneumiot.board.board_id = pneumiot.patient.board_id;

DROP TABLE IF EXISTS board;

select * from pneumiot.board;

select * from pneumiot.sensor;

delete from pneumiot.sensor where sensor_id = 'aaa-aaa'; 

select board_id from pneumiot.board where sensor_id = 'aaa-aaa';


select * from pneumiot.patient where board_id = '123-abc-456-def';

select worker_id from pneumiot.doctor where patient_id = '76438301D';

select worker_id from pneumiot.doctor where patient_id 
IN(
  SELECT pneumiot.patient.patient_id FROM pneumiot.patient WHERE board_id IN (
    SELECT pneumiot.board.board_id FROM pneumiot.board WHERE sensor_id IN (
      SELECT pneumiot.sensor.sensor_id FROM pneumiot.sensor WHERE sensor_id = 'aaa-aaa'
      )
    )
);

select * from pneumiot.patient;

SELECT pneumiot.patient.patient_id FROM pneumiot.patient WHERE board_id IN (
    SELECT pneumiot.board.board_id FROM pneumiot.board WHERE sensor_id IN (
      SELECT pneumiot.sensor.sensor_id FROM pneumiot.sensor WHERE sensor_id = 'aaa-aaa'
      )
    ) GROUP BY pneumiot.patient.patient_id;

SELECT pneumiot.board.board_id FROM pneumiot.board WHERE sensor_id IN (
      SELECT pneumiot.sensor.sensor_id FROM pneumiot.sensor WHERE sensor_id = 'aaa-aaa'
      
    ) GROUP BY pneumiot.board.board_id;

SELECT pneumiot.sensor.sensor_id FROM pneumiot.sensor WHERE sensor_id = 'aaa-aaa';

Delete from pneumiot.doctor WHERE worker_id = '24183922C';


select * from pneumiot.hourly_average where sensor_id = 'aaa-aaa';

SELECT 
    MIN(day_date) as minDate, 
    MAX(day_date) as maxDate
FROM 
    (
        SELECT 
            day_date, 
            COUNT(*) as num_entries
        FROM 
            pneumiot.hourly_average
        WHERE 
            sensor_id in (select pneumiot.board.sensor_id 
                from pneumiot.board 
                INNER JOIN pneumiot.patient 
                ON pneumiot.patient.board_id = pneumiot.board.board_id 
                WHERE pneumiot.patient.patient_id = '76438301D' and pneumiot.board.board_id = '123-abc-456-def' LIMIT 1)
        GROUP BY 
            day_date
    ) as entry_counts
WHERE 
    num_entries = 24;

select pneumiot.board.sensor_id 
                from pneumiot.board 
                INNER JOIN pneumiot.patient 
                ON pneumiot.patient.board_id = pneumiot.board.board_id 
                WHERE pneumiot.patient.patient_id = '76438301D' and pneumiot.board.board_id = '123-abc-456-def' LIMIT 1;

SELECT 
MIN(day_date) as minDate, 
MAX(day_date) as maxDate
FROM 
(
    SELECT 
        day_date, 
        COUNT(*) as num_entries
    FROM 
        pneumiot.hourly_average
    WHERE 
        sensor_id in (select pneumiot.board.sensor_id 
            from pneumiot.board 
            INNER JOIN pneumiot.patient 
            ON pneumiot.patient.board_id = pneumiot.board.board_id 
            WHERE pneumiot.patient.patient_id = '76438301D' LIMIT 1)
          and pneumiot.hourly_average.board_id = '123-abc-456-def'
    GROUP BY 
        day_date
) as entry_counts
WHERE 
num_entries = 24;

select * from pneumiot.daily_average;

select * from pneumiot.monthly_average;

SELECT board_id from pneumiot.patient where patient_id = '76438301D';

select pneumiot.board.sensor_id 
from pneumiot.board 
INNER JOIN pneumiot.patient 
ON pneumiot.patient.board_id = pneumiot.board.board_id 
WHERE pneumiot.patient.patient_id = '76438301D' LIMIT 1;

select * from pneumiot.daily_average where pneumiot.daily_average.sensor_id IN (
  select pneumiot.board.sensor_id 
  from pneumiot.board 
  INNER JOIN pneumiot.patient 
  ON pneumiot.patient.board_id = pneumiot.board.board_id 
  WHERE pneumiot.patient.patient_id = '76438301D'
);

select pneumiot.sensor.sensor_type, pneumiot.sensor.sensor_id from pneumiot.sensor where pneumiot.sensor.sensor_id IN (
  Select pneumiot.hourly_average.sensor_id
  from pneumiot.hourly_average 
  where patient_id = '76438301D' 
  and board_id = '987-zxc-654-ytr'
  and day_date = '2023-07-01'
);
select average_measure as average, hour_time 
from pneumiot.hourly_average where 
sensor_id = 'ddd-ddd' 
and patient_id = '76438301D' 
and day_date = '2023-07-11'; 


select average_measure as average, hour_time 
from pneumiot.hourly_average where 
sensor_id = 'aaa-aaa' 
and patient_id = '76438301D' 
and day_date = '2023-07-11'; 


select average_measure as average, hour_time 
from pneumiot.hourly_average where 
sensor_id = 'aaa-aaa' 
and patient_id = '76438301D' 
and day_date = '2023-07-11'; 


SELECT * from pneumiot.daily_average where sensor_id = 'aaa-aaa' and patient_id = '76438301D' and month_id = 7;



select pneumiot.sensor.sensor_type, pneumiot.sensor.sensor_id from pneumiot.sensor where pneumiot.sensor.sensor_id IN (
    Select pneumiot.daily_average.sensor_id
    from pneumiot.daily_average 
    where 
     patient_id = '76438301D'
    and month_id = 7
  );




SELECT 
    month_id
FROM 
    pneumiot.daily_average
GROUP BY 
    month_id
HAVING 
    COUNT(DISTINCT daily_day) > 0;


select * from pneumiot.monthly_average where sensor_id = 'aaa-aaa' and patient_id = '76438301D';
    SELECT 
    year_date
FROM 
    pneumiot.monthly_average
GROUP BY 
    year_date
HAVING 
    COUNT(DISTINCT month_number) > 0;

select pneumiot.sensor.sensor_type, pneumiot.sensor.sensor_id from pneumiot.sensor where pneumiot.sensor.sensor_id IN (
  Select pneumiot.monthly_average.sensor_id
  from pneumiot.monthly_average 
  where patient_id = '76438301D' 
  and year_date = 2023
);


select average_measure as average, month_number as date_time
from pneumiot.monthly_average where 
sensor_id = 'aaa-aaa' 
and patient_id = '76438301D' 
and year_date = 2023; 


SELECT  pneumiot.doctor.patient_id, board_id, discharge_date, admission_date
FROM pneumiot.patient
INNER JOIN pneumiot.doctor
ON pneumiot.patient.patient_id = pneumiot.doctor.patient_id
WHERE pneumiot.doctor.worker_id = '24183922C';



SELECT year_date
FROM pneumiot.monthly_average WHERE patient_id = '76438301D' and board_id= '123-abc-456-def' and year_date = 2023
GROUP BY 
    year_date
HAVING COUNT(DISTINCT month_number) > 0;


SELECT average_measure as average, daily_day as data_time
FROM pneumiot.daily_average 
WHERE sensor_id = $1 
    AND patient_id = $awda2 
    AND month_id = $3
    and board_id = $4;


SELECT  event_patient_id, pneumiot.doctor.patient_id, board_id, discharge_date, admission_date
FROM pneumiot.patient
INNER JOIN pneumiot.doctor
ON pneumiot.patient.patient_id = pneumiot.doctor.patient_id
WHERE pneumiot.doctor.worker_id = '24183922C';

select * from pneumiot.worker_auth;