-- Active: 1688058502640@@127.0.0.1@5432@PneumlOT@public
-- Generated by the database client, not guaranteed complete.
CREATE TABLE IF NOT EXISTS pneumiot.sensor_log (
    log_id SERIAL NOT NULL,
    board_id character varying(50) REFERENCES pneumiot.board (board_id),
    log_message character varying(250),
    PRIMARY KEY(log_id)
);

INSERT INTO pneumiot.sensor_log (board_id, log_message)
SELECT b.board_id, 'Mensaje de registro' -- Reemplaza 'Mensaje de registro' con el mensaje deseado
FROM pneumiot.board b
CROSS JOIN generate_series(1, 20) AS v;


SELECT * from pneumiot.sensor_log;

DROP TABLE IF EXISTS pneumiot.sensor_log;