version: 2.1
orbs:
  python: circleci/python@2.0.3

env:
  COMPOSE_FILE: docker/docker-compose.test.yml
jobs:
    test_docker:
      machine:
        image: ubuntu-2004:202010-01
      steps:
        - checkout
        - run:
            name: "Docker compose tests for database"
            command: |
              docker pull spl720/test_python_database:latest
              docker pull spl720/test_database:latest
              docker-compose -f docker/docker-compose.test.yml run test   
              
workflows:
  test_my_app:
    jobs:
      - test_docker