version: "3.9"

services:
  frontend:
    build:
      context: ./app/frontend
    image: spl720/frontend:latest
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    build:
      context: ./app/backend
    image: spl720/backend:latest
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    build:
      context: ./app/database
    image: spl720/database:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
