FROM postgres
ENV POSTGRES_USER myuser
ENV POSTGRES_PASSWORD docker
ENV POSTGRES_DB pneumiot
COPY init_creation.sql /docker-entrypoint-initdb.d/
COPY insert_random_data.sql /docker-entrypoint-initdb.d/