name: ci

on:
  push:
    paths:
      - 'app/database/pyproject.toml'
      - 'app/database/poetry.lock'
      - 'docker/test/database/test.dockerfile'
      - 'docker/test/database/test.pythonEnv.dockerfile'
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: spl720/test_database
            dockerfile: docker/test/database/test.dockerfile
          - image: spl720/test_python_database
            dockerfile: docker/test/database/test.pythonEnv.dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Configure Docker for GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} docker.pkg.github.com --password-stdin

      - name: Publish to GitHub Packages
        run: docker tag ${{ matrix.image }} docker.pkg.github.com/${{ github.repository }}/${{ matrix.image }}:${{ steps.meta.outputs.tags }}
        
      - name: Push to GitHub Packages
        run: docker push docker.pkg.github.com/${{ github.repository }}/${{ matrix.image }}:${{ steps.meta.outputs.tags }}
